// Generated by gencpp from file virtual_tactile_pad/ContactForce.msg
// DO NOT EDIT!


#ifndef VIRTUAL_TACTILE_PAD_MESSAGE_CONTACTFORCE_H
#define VIRTUAL_TACTILE_PAD_MESSAGE_CONTACTFORCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace virtual_tactile_pad
{
template <class ContainerAllocator>
struct ContactForce_
{
  typedef ContactForce_<ContainerAllocator> Type;

  ContactForce_()
    : header()
    , position()
    , force()  {
    }
  ContactForce_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , force(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _force_type;
  _force_type force;





  typedef boost::shared_ptr< ::virtual_tactile_pad::ContactForce_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::virtual_tactile_pad::ContactForce_<ContainerAllocator> const> ConstPtr;

}; // struct ContactForce_

typedef ::virtual_tactile_pad::ContactForce_<std::allocator<void> > ContactForce;

typedef boost::shared_ptr< ::virtual_tactile_pad::ContactForce > ContactForcePtr;
typedef boost::shared_ptr< ::virtual_tactile_pad::ContactForce const> ContactForceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::virtual_tactile_pad::ContactForce_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::virtual_tactile_pad::ContactForce_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::virtual_tactile_pad::ContactForce_<ContainerAllocator1> & lhs, const ::virtual_tactile_pad::ContactForce_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.force == rhs.force;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::virtual_tactile_pad::ContactForce_<ContainerAllocator1> & lhs, const ::virtual_tactile_pad::ContactForce_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace virtual_tactile_pad

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::virtual_tactile_pad::ContactForce_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::virtual_tactile_pad::ContactForce_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::virtual_tactile_pad::ContactForce_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::virtual_tactile_pad::ContactForce_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::virtual_tactile_pad::ContactForce_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::virtual_tactile_pad::ContactForce_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::virtual_tactile_pad::ContactForce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "119578e63107ee6e9e345005dd73edb3";
  }

  static const char* value(const ::virtual_tactile_pad::ContactForce_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x119578e63107ee6eULL;
  static const uint64_t static_value2 = 0x9e345005dd73edb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::virtual_tactile_pad::ContactForce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "virtual_tactile_pad/ContactForce";
  }

  static const char* value(const ::virtual_tactile_pad::ContactForce_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::virtual_tactile_pad::ContactForce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Vector3 force\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::virtual_tactile_pad::ContactForce_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::virtual_tactile_pad::ContactForce_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.force);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContactForce_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::virtual_tactile_pad::ContactForce_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::virtual_tactile_pad::ContactForce_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "force: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.force);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VIRTUAL_TACTILE_PAD_MESSAGE_CONTACTFORCE_H
